import React from "react";
import ReactDataGrid from "@inovua/reactdatagrid-community";
import "@inovua/reactdatagrid-community/index.css";

// reactstrap components
import { Container, Row, Col } from "reactstrap";

// const filterYagneekamValue = [
//   { name: "Name", operator: "contains", type: "string", value: "" },
//   { name: "Place", operator: "contains", type: "string", value: "" },
//   { name: "Mobile", operator: "gte", type: "number", value: "" },
//   { name: "Landline", operator: "gte", type: "number", value: "" },
// ];
// core components
// const yagneekamColumns = [
//   { name: "Sno", header: "Sno", minWidth: 10, maxWidth: 70, defaultFlex: 1 },
//   { name: "Name", header: "Name", minWidth: 500, defaultFlex: 1, render: ({ data }) => data.prefix + " " + data.Surname + " " + data.Name, type: "string" },
//   { name: "Place", header: "Place", minWidth: 120, maxWidth: 500, defaultFlex: 1 },
//   { name: "Mobile", header: "Mobile", minWidth: 120, maxWidth: 150, defaultFlex: 1, type: "number" },
//   { name: "Landline", header: "Landline", minWidth: 120, maxWidth: 150, defaultFlex: 1, type: "number" },
// ];
// define grid styles here
const gridStyle = { minHeight: 550 };
// define tabular data here
// const yaagnikamList = [
//   {
//     Sno: 1,
//     prefix: "Sriman",
//     Surname: "Rompicherla",
//     Name: "Sriramachandra Bhatta Charyulu (Rambabu)",
//     Place: "Krapa",
//     Mobile: 8500653643,
//     Landline: "08644-243557",
//   },
//   {
//     Sno: 2,
//     prefix: "Sriman",
//     Surname: "Parasaram",
//     Name: "RamakrishnamaCharyulu",
//     Place: "Kummamuru",
//     Mobile: 9290879012,
//     Landline: "",
//   },
//   {
//     Sno: 3,
//     prefix: "Sriman",
//     Surname: "Vedantam",
//     Name: "SeshaCharyulu",
//     Place: "Baliparru",
//     Mobile: 9441370746,
//     Landline: "",
//   },
//   {
//     Sno: 4,
//     prefix: "Sriman",
//     Surname: "Sudarshanam",
//     Name: "Yogananda Lakshmi NarasimhaCharyulu",
//     Place: "Nimmakuru",
//     Mobile: 9949369587,
//     Landline: "",
//   },
//   {
//     Sno: 5,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "RamaCharyulu",
//     Place: "Gudivada",
//     Mobile: 9849215140,
//     Landline: "",
//   },
//   {
//     Sno: 6,
//     prefix: "Sriman",
//     Surname: "Brindavanam",
//     Name: "RamakrishnamaCharyulu",
//     Place: "Karlapalem",
//     Mobile: 9492709364,
//     Landline: "",
//   },
//   {
//     Sno: 7,
//     prefix: "Sriman",
//     Surname: "Muttevi",
//     Name: "Srinivasa Sasikanth",
//     Place: "Machilipatnam",
//     Mobile: 9440440312,
//     Landline: "",
//   },
//   {
//     Sno: 8,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "RamakrishnamaCharyulu",
//     Place: "Barlapudi",
//     Mobile: 9441195055,
//     Landline: "",
//   },
//   {
//     Sno: 9,
//     prefix: "Sriman",
//     Surname: "Parasaram",
//     Name: "Yogananda Satya Murty",
//     Place: "Yakamuru",
//     Mobile: 9912128599,
//     Landline: "",
//   },
//   {
//     Sno: 10,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "VamsiKrishna",
//     Place: "Vijayawada",
//     Mobile: 9441014623,
//     Landline: "",
//   },
//   {
//     Sno: 11,
//     prefix: "Sriman",
//     Surname: "Parasaram",
//     Name: "Krishna Prasad",
//     Place: "Batlapenumarru",
//     Mobile: 9866912677,
//     Landline: "",
//   },
//   {
//     Sno: 12,
//     prefix: "Sriman",
//     Surname: "Parankusam",
//     Name: "Seeta RamaCharyulu",
//     Place: "Penuganjiprolu",
//     Mobile: 9390140751,
//     Landline: "",
//   },
//   {
//     Sno: 13,
//     prefix: "Sriman",
//     Surname: "Narayanam",
//     Name: "Naga MohanaCharyulu",
//     Place: "Vijayawada",
//     Mobile: 9676623404,
//     Landline: "",
//   },
//   {
//     Sno: 14,
//     prefix: "Sriman",
//     Surname: "Muttevi",
//     Name: "SatyanarayanaCharyulu",
//     Place: "Manginapudi",
//     Mobile: 9440220305,
//     Landline: "",
//   },
//   {
//     Sno: 15,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "Raghunatha Sharma",
//     Place: "Machilipatnam",
//     Mobile: 9490338461,
//     Landline: "",
//   },
//   {
//     Sno: 16,
//     prefix: "Sriman",
//     Surname: "Pulipaka",
//     Name: "Chaitanya",
//     Place: "Kolavennu",
//     Mobile: 9949179038,
//     Landline: "",
//   },
//   {
//     Sno: 17,
//     prefix: "Sriman",
//     Surname: "Tamirisa",
//     Name: "VamsiKrishna",
//     Place: "Potarlanka",
//     Mobile: 9912303191,
//     Landline: "",
//   },
//   {
//     Sno: 18,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "P V Trinath",
//     Place: "Gudivada",
//     Mobile: 9963052587,
//     Landline: "",
//   },
//   {
//     Sno: 19,
//     prefix: "Sriman",
//     Surname: "Vedantam",
//     Name: "Ananta SrinivasaCharyulu",
//     Place: "Penamaluru",
//     Mobile: 9441177265,
//     Landline: "",
//   },
//   {
//     Sno: 20,
//     prefix: "Sriman",
//     Surname: "Rompicherla",
//     Name: "DattuKumar Acharyulu",
//     Place: "Nunna",
//     Mobile: 9000198512,
//     Landline: "",
//   },
//   {
//     Sno: 21,
//     prefix: "Sriman",
//     Surname: "Sudarshanam",
//     Name: "Maruthi Sesha VaraPrasad",
//     Place: "Ibrahimpatnam",
//     Mobile: 9394565758,
//     Landline: "",
//   },
//   {
//     Sno: 22,
//     prefix: "Sriman",
//     Surname: "Parasaram",
//     Name: "YogaNanada SatyaMurty",
//     Place: "Yakamuru",
//     Mobile: 9912128599,
//     Landline: "",
//   },
//   {
//     Sno: 23,
//     prefix: "Sriman",
//     Surname: "Tamirisa",
//     Name: "Veda Prakash",
//     Place: "Garikaparru",
//     Mobile: 9492484900,
//     Landline: "",
//   },
//   {
//     Sno: 24,
//     prefix: "Sriman",
//     Surname: "Muttevi",
//     Name: "Madhava Goutham",
//     Place: "KuruMaddali",
//     Mobile: 9550810540,
//     Landline: "",
//   },
//   {
//     Sno: 25,
//     prefix: "Sriman",
//     Surname: "Brindavanam",
//     Name: "Yogananda Lakshmi NarasimhaCharyulu",
//     Place: "Ibrahimpatnam",
//     Mobile: 8106758565,
//     Landline: "",
//   },
//   {
//     Sno: 26,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "HariNaveen",
//     Place: "Rayanapadu",
//     Mobile: 9000069093,
//     Landline: "",
//   },
//   {
//     Sno: 27,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "Narasimha GopalaCharyulu",
//     Place: "Tamirisa",
//     Mobile: 9441177324,
//     Landline: "",
//   },
//   {
//     Sno: 28,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "HariKrishnamaCharyulu",
//     Place: "Pedana",
//     Mobile: 9000997814,
//     Landline: "",
//   },
//   {
//     Sno: 29,
//     prefix: "Sriman",
//     Surname: "Brindavanam",
//     Name: "Madhu SudhanaCharyulu",
//     Place: "Turpudigavalli",
//     Mobile: 9701560802,
//     Landline: "",
//   },
//   {
//     Sno: 30,
//     prefix: "Sriman",
//     Surname: "Sudarshanam",
//     Name: "Venkatesh",
//     Place: "ChandraGudem",
//     Mobile: 9502942687,
//     Landline: "",
//   },
//   {
//     Sno: 31,
//     prefix: "Sriman",
//     Surname: "Devayajanam",
//     Name: "RamaCharyulu",
//     Place: "GampalaGudem",
//     Mobile: 9963929890,
//     Landline: "",
//   },
//   {
//     Sno: 32,
//     prefix: "Sriman",
//     Surname: "Rompicherla",
//     Name: "Venkata PhaniRam",
//     Place: "Kodali",
//     Mobile: 9963658663,
//     Landline: "",
//   },
//   {
//     Sno: 33,
//     prefix: "Sriman",
//     Surname: "Vedantam",
//     Name: "HayaGreevaCharyulu",
//     Place: "DarbhakuPalli",
//     Mobile: 9959135814,
//     Landline: "",
//   },
//   {
//     Sno: 34,
//     prefix: "Sriman",
//     Surname: "Brindavanam",
//     Name: "Veera RaghavaCharyulu",
//     Place: "Tarakaturu",
//     Mobile: 9948882922,
//     Landline: "",
//   },
//   {
//     Sno: 35,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "Lakshmi NarasimhaCharyulu",
//     Place: "Aganiparru",
//     Mobile: 9032289406,
//     Landline: "",
//   },
//   {
//     Sno: 36,
//     prefix: "Sriman",
//     Surname: "Deevi",
//     Name: "Pattabhi RamaCharyulu",
//     Place: "M.Chitturu",
//     Mobile: 9177570276,
//     Landline: "",
//   },
//   {
//     Sno: 37,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "Mithun",
//     Place: "Varahapatnam",
//     Mobile: 9866114610,
//     Landline: "",
//   },
//   {
//     Sno: 38,
//     prefix: "Sriman",
//     Surname: "Vedantam",
//     Name: "SravanaDattu",
//     Place: "VanaPamula",
//     Mobile: 8464018951,
//     Landline: "",
//   },
//   {
//     Sno: 39,
//     prefix: "Sriman",
//     Surname: "Rompicherla",
//     Name: "Bhattar Srikanth",
//     Place: "Aakulamannadu",
//     Mobile: 9959610574,
//     Landline: "",
//   },
//   {
//     Sno: 40,
//     prefix: "Sriman",
//     Surname: "Vedantam",
//     Name: "Prasad",
//     Place: "Vanukuru",
//     Mobile: 9959831591,
//     Landline: "",
//   },
//   {
//     Sno: 41,
//     prefix: "Sriman",
//     Surname: "",
//     Name: "Lakshmi Narayana",
//     Place: "Nimmakuru",
//     Mobile: 9603352390,
//     Landline: "",
//   },
//   {
//     Sno: 42,
//     prefix: "Sriman",
//     Surname: "Muttevi",
//     Name: "Phani Srinivas",
//     Place: "Guntupalli",
//     Mobile: 7396351669,
//     Landline: "",
//   },
//   {
//     Sno: 43,
//     prefix: "Sriman",
//     Surname: "Srinivasula",
//     Name: "SatyaSaran",
//     Place: "Nutakki",
//     Mobile: 8008070743,
//     Landline: "",
//   },
//   {
//     Sno: 44,
//     prefix: "Sriman",
//     Surname: "Muttevi",
//     Name: "Sitaram",
//     Place: "Muvva",
//     Mobile: 9866640696,
//     Landline: "",
//   },
//   {
//     Sno: 45,
//     prefix: "Sriman",
//     Surname: "Rompicherla",
//     Name: "Ramesh",
//     Place: "Gundrayi",
//     Mobile: 9441173133,
//     Landline: "",
//   },
//   {
//     Sno: 46,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "Lakshmi NarasimhaCharyulu",
//     Place: "Poolla, Elluru",
//     Mobile: 9963241944,
//     Landline: "",
//   },
//   {
//     Sno: 47,
//     prefix: "Sriman",
//     Surname: "Agnihotram",
//     Name: "RamaCharyulu",
//     Place: "Gudivada",
//     Mobile: 9849215140,
//     Landline: "",
//   },
// ];

const aparamGridColumns = [
  { name: "Sno", header: "Sno", minWidth: 10, maxWidth: 70,  defaultFlex: 1 },
  { name: "Name", header: "Name", minWidth: 500, defaultFlex: 1, render: ({ data }) => data.prefix + " " + data.Surname + " " + data.Name, type: "string" },
  { name: "Place", header: "Place", minWidth: 120, maxWidth: 500, defaultFlex: 1 },
  { name: "Mobile", header: "Mobile", minWidth: 120, maxWidth: 150, defaultFlex: 1, type: "number" },
  { name: "Landline", header: "Landline", minWidth: 150, maxWidth: 200, defaultFlex: 1, type: "number" },
];

const filterAparamList = [
  { name: "Name", operator: "contains", type: "string", value: "" },
  { name: "Place", operator: "contains", type: "string", value: "" },
  { name: "Mobile", operator: "gte", type: "number", value: "" },
  { name: "Landline", operator: "gte", type: "number", value: "" },
];

const aparamList = [
  {
    Sno: 1,
    prefix: "Sriman",
    Surname: "Rompicherla",
    Name: "Sriramachandra Bhatta Charyulu (Rambabu)",
    Place: "Krapa, Kolluru(M)",
    Mobile: 8500653643,
    Landline: "08644-243557",
  },
  {
    Sno: 2,
    prefix: "Sriman",
    Surname: "Agnihotram",
    Name: "Lakshmi NarasimhaCharyulu",
    Place: "Poolla, Elluru",
    Mobile: 9963241944,
    Landline: "",
  },
  {
    Sno: 3,
    prefix: "Sriman",
    Surname: "Brundavanam",
    Name: "Aditya",
    Place: "Prathipadu, Guntur",
    Mobile: 9849282995,
    Landline: 9000276126,
  },
  {
    Sno: 4,
    prefix: "Sriman",
    Surname: "Brundavanam",
    Name: "Ramakrishnama Charyulu",
    Place: "Karlapallem",
    Mobile: 9492709364,
    Landline: "",
  },
  {
    Sno: 5,
    prefix: "Sriman",
    Surname: "Brundavanam",
    Name: "Srinivasa Charyulu",
    Place: "Tarakaturu",
    Mobile: 9440163025,
    Landline: "087672-244621",
  },
  {
    Sno: 6,
    prefix: "Sriman",
    Surname: "Agnihotram",
    Name: "RamaCharyulu",
    Place: "Gudivada",
    Mobile: 9849215140,
    Landline: "",
  },
  {
    Sno: 7,
    prefix: "Sriman",
    Surname: "Deevi",
    Name: "VenkataCharyulu",
    Place: "Jaggapuram",
    Mobile: 0,
    Landline: "",
  },
  {
    Sno: 8,
    prefix: "Sriman",
    Surname: "Paramkusham",
    Name: "Badari Srinivas",
    Place: "Tammara, near Kodada",
    Mobile: 9866363471,
    Landline: "",
  },
  {
    Sno: 9,
    prefix: "Sriman",
    Surname: "Paramkusham",
    Name: "Ananta Venkata Ranganadha Deekshitulu ",
    Place: "Gundlapalli, Prakasam (Dt)",
    Mobile: 9849195100,
    Landline: "",
  },
  {
    Sno: 10,
    prefix: "Sriman",
    Surname: "Parasaram",
    Name: "Bhogasrinivasa Varaprasad",
    Place: "Chebrolu",
    Mobile: 9885163492,
    Landline: "",
  },
  {
    Sno: 11,
    prefix: "Sriman",
    Surname: "Parasaram",
    Name: "Ramakrishnama Charyulu",
    Place: "Kummamuru",
    Mobile: 9290879012,
    Landline: "",
  },
  {
    Sno: 12,
    prefix: "Sriman",
    Surname: "Peddinti",
    Name: "SriVijayacharya",
    Place: "Annapurna Nagar, Gorantla",
    Mobile: 0,
    Landline: "",
  },
  {
    Sno: 13,
    prefix: "Sriman",
    Surname: "Peddinti",
    Name: "Venkata Ratnababu",
    Place: "Arrandal Pet, Guntur",
    Mobile: 9293000386,
    Landline: "0863-2335515",
  },
  {
    Sno: 14,
    prefix: "Sriman",
    Surname: "Ratnakaram",
    Name: "Padmanabha Charyulu",
    Place: "Rompicherla",
    Mobile: 9440776640,
    Landline: "",
  },
  {
    Sno: 15,
    prefix: "Sriman",
    Surname: "Ratnakaram",
    Name: "RamaKrishna Deekshitulu",
    Place: "Aagiripalli",
    Mobile: 9985565495,
    Landline: "",
  },
  {
    Sno: 16,
    prefix: "Sriman",
    Surname: "Rompicherla",
    Name: "Badarinarayana Charyulu ",
    Place: "Chamallamudi, Guntur (Dt)",
    Mobile: 9492469591,
    Landline: "08632-287413",
  },
  {
    Sno: 17,
    prefix: "Sriman",
    Surname: "Rompicherla",
    Name: "Sesha Charyulu",
    Place: "Nunna",
    Mobile: 7793914897,
    Landline: "",
  },
  {
    Sno: 18,
    prefix: "Sriman",
    Surname: "Sudarsanam",
    Name: "LakshmiNarasimha Charyulu",
    Place: "Nimmakuru",
    Mobile: 9949369587,
    Landline: "",
  },
  {
    Sno: 19,
    prefix: "Sriman",
    Surname: "Tamirisa",
    Name: "Vamshi Krishna",
    Place: "Potarlanka",
    Mobile: 9912303191,
    Landline: "",
  },
  {
    Sno: 20,
    prefix: "Sriman",
    Surname: "Vedantam",
    Name: "Sesha Charyulu",
    Place: "Balliparru",
    Mobile: 9441370746,
    Landline: "",
  },
  {
    Sno: 21,
    prefix: "Sriman",
    Surname: "Vinukonda",
    Name: "Murali Krishna Charyulu",
    Place: "Potarlanka",
    Mobile: 9949563018,
    Landline: "",
  },
  {
    Sno: 22,
    prefix: "Sriman",
    Surname: "Parankusam",
    Name: "Seetarama Charyulu",
    Place: "Penuganjiprolu",
    Mobile: 9390140751,
    Landline: "",
  },
  {
    Sno: 23,
    prefix: "Sriman",
    Surname: "Agnihotram",
    Name: "P V Trinath",
    Place: "Gudivada",
    Mobile: 9963052587,
    Landline: "",
  },
  {
    Sno: 24,
    prefix: "Sriman",
    Surname: "Deevi",
    Name: "Gopala Charyulu",
    Place: "Tamirisa, Krishna (Dt)",
    Mobile: 7013884888,
    Landline: "",
  },
  {
    Sno: 25,
    prefix: "Sriman",
    Surname: "Deevi",
    Name: "Uday Kumar",
    Place: "Penumudi, Bapatla (Dt)",
    Mobile: 9912411898,
    Landline: "",
  },
  {
    Sno: 26,
    prefix: "Sriman",
    Surname: "Deevi",
    Name: "Murali Krishna",
    Place: "Yanamadala",
    Mobile: 9912026253,
    Landline: "",
  },
  {
    Sno: 27,
    prefix: "Sriman",
    Surname: "Deevi",
    Name: "Seetarama Murthy",
    Place: "Eemani",
    Mobile: 9848699456,
    Landline: "",
  },
  {
    Sno: 28,
    prefix: "Sriman",
    Surname: "N S R",
    Name: "Bhattar",
    Place: "Karumuru, Bapatla (Dt)",
    Mobile: 9290236418,
    Landline: "",
  },
  {
    Sno: 29,
    prefix: "Sriman",
    Surname: "Parasaram",
    Name: "Srinivasa Charyulu",
    Place: "Tirupathi",
    Mobile: 9912449889,
    Landline: "",
  },
  {
    Sno: 30,
    prefix: "Sriman",
    Surname: "Parasaram",
    Name: "Vijitendra",
    Place: "Gorantla, Guntur (Dt)",
    Mobile: 8639760097,
    Landline: "",
  },
  {
    Sno: 31,
    prefix: "Sriman",
    Surname: "Parasaram",
    Name: "RamaChandra Charyulu (Ramesh)",
    Place: "Pamidimarru, Bapatla (Dt)",
    Mobile: 9848305843,
    Landline: "",
  },
  {
    Sno: 32,
    prefix: "Sriman",
    Surname: "Peddinti",
    Name: "Seetarama Prasad",
    Place: "Mallapur, Hyderabad",
    Mobile: 9848617791,
    Landline: "",
  },
  {
    Sno: 33,
    prefix: "Sriman",
    Surname: "Rompicherla",
    Name: "Venkata Satyanarayana Charyulu",
    Place: "Tirupathi",
    Mobile: 9440478760,
    Landline: "",
  },
  {
    Sno: 34,
    prefix: "Sriman",
    Surname: "Sribhashyam",
    Name: "Anil Kumar",
    Place: "Katevaram",
    Mobile: 8074527486,
    Landline: 9885938595,
  },
  {
    Sno: 35,
    prefix: "Sriman",
    Surname: "Tamirisa",
    Name: "Govardhana Charyulu",
    Place: "Kotanemalipuri, Palnadu (Dt)",
    Mobile: 9834122854,
    Landline: "",
  },
  {
    Sno: 36,
    prefix: "Sriman",
    Surname: "Udayagiri",
    Name: "Ananta Nayarayana Chayulu",
    Place: "Alluru, Nelluru (Dt)",
    Mobile: 9849494981,
    Landline: "",
  },
];

function Purohitas() {
  return (
    <>
      <div className="cd-section" id="purohitas">
        <div className="team-1">
          <Container>
           {/* <Row>
              <Col className="ml-auto mr-auto text-center" md="12">
                <h2 className="title">Vaikhanasa Purohitulu</h2>
                 <h4>
                  Below the list of vaikanasa purohit's who perform yaagnikam :
                </h4>
                <br />
                <br />
                <ReactDataGrid
                  idProperty="id1"
                  columns={yagneekamColumns}
                  dataSource={yaagnikamList}
                  style={gridStyle}
                  defaultFilterValue={filterYagneekamValue}
                  reorderColumns={false}
                /> 
              </Col>
            </Row>*/}
            <Row>
              <Col className="ml-auto mr-auto text-center" md="12">
                <h2 className="title">Vaikhanasa Purohitulu</h2>                
                <h4>Following are vaikhanasa purohits who perform aparam :</h4>
                <ReactDataGrid
                  idProperty="id"
                  columns={aparamGridColumns}
                  dataSource={aparamList}
                  style={gridStyle}
                  defaultFilterValue={filterAparamList}
                  reorderColumns={false}
                />
              </Col>
            </Row>
          </Container>
        </div>
      </div>
    </>
  );
}

export default Purohitas;
