name: FTP Deploy

on:
  push:
    branches:
      - main   # or whichever branch you want to deploy

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # or the version your React app uses

      - name: Install dependencies
        working-directory: ./client
        run: npm install --legacy-peer-deps

      - name: Build React app
        working-directory: ./client
        run: npm run build

      - name: Deploy build folder to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /manavaikhanasam.com/   # replace with your directory
          local-dir: ./client/build/
